const router = require('express').Router();
const authRoute = require('./auth.route');
const userRoute = require('./user.route');
const roleRoute = require('./role.route');
const menuRoute = require('./menu.route');
const golonganKelasRoute = require('./golonganKelas.route');
const jurusanRoute = require('./jurusan.route');
const sumberInformasiRoute = require('./sumberInformasi.route');
const ukuranAlmamaterRoute = require('./ukuranAlmamater.route');
const pembayaranRoute = require('./pembayaran.route');
const dokumenPendaftaranRoute = require('./dokumenPendaftaran.route');
const dokumenKelengkapanRoute = require('./dokumenKelengkapan.route');
const gelombangRoute = require('./gelombang.route');
const pesertaRoute = require('./peserta.route');
const kampusRoute = require('./kampus.route');
const beasiswaRoute = require('./beasiswa.route');
const biayaKuliahRoute = require('./biayaKuliah.route');
const calonMahasiswaRoute = require('./calonMahasiswa.route');
const mahasiswaRoute = require('./mahasiswa.route');
const homeImageRoute = require('./homeImage.route');
const auditLogRoute = require('./auditLog.route');
const karyawanRoute = require('./karyawan.route');
const dosenRoute = require('./dosen.route');
const jadwalKuliahRoute = require('./jadwalKuliah.route');
const kehadiranDosenRoute = require('./kehadiranDosen.route');
const nilaiMahasiswaRoute = require('./nilaiMahasiswa.route');
const yudisiumRoute = require('./yudisium.route');
const laporanIjazahRoute = require('./laporanIjazah.route');
const laporanRealisasiRoute = require('./laporanRealisasi.route');
const suratKeteranganRoute = require('./suratKeterangan.route');
const laporanKehadiranMengajarRoute = require('./laporanKehadiranMengajar.route');
const laporanMahasiswaPerkelasRoute = require('./laporanMahasiswaPerkelas.route');
const laporanKhsRoute = require('./laporanKhs.route');
const tahunAjaranRoute = require('./tahunAjaran.route');
const mataKuliahRoute = require('./mataKuliah.route');
const krsRoute = require('./krs.route');
const prodiLulusanRoute = require('./prodiLulusan.route');
const jadwalSidangRoute = require('./jadwalSidang.route');
const pendaftarSidangRoute = require('./pendaftarSidang.route');
const pembimbingMagangRoute = require('./pembimbingMagang.route');
const pembimbingTaSkripsiRoute = require('./pembimbingTaSkripsi.route');
const pembimbingAkademikRoute = require('./pembimbingAkademik.route');
const nilaiPerkelasRoute = require('./nilaiPerkelas.route');
const bimbinganMagangRoute = require('./bimbinganMagang.route');
const vocDosenFtidRoute = require('./vocDosenFtid.route');
const vocUjianFtidRoute = require('./vocUjianFtid.route');
const kurikulumRoute = require('./kurikulum.route');
const konversiKurikulumRoute = require('./konversiKurikulum.route');
const biodataMahasiswaRoute = require('./biodataMahasiswa.route');
const createSyncFingerRoute = require('./syncFingerLog.route');
const dinasCutiLupaFingerRoute = require('./dinasCutiLupaFinger.route');
const reportFingerRoute = require('./reportFinger.route');
const keringananRoute = require('./keringanan.route');
const tarifTaSkripsiRoute = require('./tarifTaSkripsi.route');
const tarifPembimbingRoute = require('./tarifPembimbing.route');
const tarifLainRoute = require('./tarifLain.route');
const tarifKuliahRoute = require('./tarifKuliah.route');
const daftarPotonganRoute = require('./daftarPotongan.route');
const vocUjianRoute = require('./vocUjian.route');
const pembayaranSertifikasiRoute = require('./pembayaranSertifikasi.route');
const pembayaranWisudaRoute = require('./pembayaranWisuda.route');
const dosenPortalRoute = require('./dosenPortal.route');
const mahasiswaPortalRoute = require('./mahasiswaPortal.route');
const simStudentBodyRoute = require('./simStudentBody.route');
const simPresentaseKehadiranRoute = require('./simPresentaseKehadiran.route');
const simKehadiranKelasRoute = require('./simKehadiranKelas.route');
const simFrsRoute = require('./simFrs.route');
const simLaporanUjianRoute = require('./simLaporanUjian.route');
const laporanAktifRoute = require('./laporanAktif.route');
const simIpkRoute = require('./simIpk.route');
const simLulusanRoute = require('./simLulusan.route');
const simNilaiDERoute = require('./simNilaiDE.route');
const simKehadiranMengajarRoute = require('./simKehadiranMengajar.route');
const simRekapitulasiPengajaranRoute = require('./simRekapitulasiPengajaran.route');
const tunggakanMahasiswaRoute = require('./tunggakanMahasiswa.route');
const tagihanKuliahRoute = require('./tagihanKuliah.route');
const pembayaranKuliahRoute = require('./pembayaranKuliah.route');
const perpanjanganTaSkripsiRoute = require('./perpanjanganTaSkripsi.route');
const pembayaranTaSkripsiRoute = require('./pembayaranTaSkripsi.route');
const pembayaranLainRoute = require('./pembayaranLain.route');
const pembayaranSpRoute = require('./pembayaranSp.route');
const laporanKeuanganRoute = require('./laporanKeuangan.route');
const akuntansiRoute = require('./akuntansi.route');
const kasirDashboardRoute = require('./kasirDashboard.route');
const publicRoute = require('./public.route');
const MENU = require('../constants/menuCodes');

router.use('/public', publicRoute);
router.use('/auth', authRoute);
router.use('/users', userRoute);
router.use('/roles', roleRoute);
router.use('/menus', menuRoute);
router.use('/golongan-kelas', golonganKelasRoute);
router.use('/jurusan', jurusanRoute);
router.use('/sumber-informasi', sumberInformasiRoute);
router.use('/ukuran-almamater', ukuranAlmamaterRoute);
router.use('/pembayaran', pembayaranRoute);
router.use('/dokumen-pendaftaran', dokumenPendaftaranRoute);
router.use('/dokumen-kelengkapan', dokumenKelengkapanRoute);
router.use('/gelombang', gelombangRoute);
router.use('/peserta', pesertaRoute);
router.use('/kampus', kampusRoute);
router.use('/beasiswa', beasiswaRoute);
router.use('/biaya-kuliah', biayaKuliahRoute);
router.use('/calon-mahasiswa', calonMahasiswaRoute);
router.use('/mahasiswa', mahasiswaRoute);
router.use('/home-images', homeImageRoute);
router.use('/audit-logs', auditLogRoute);
router.use('/dosen', dosenRoute);
router.use('/karyawan', karyawanRoute);
router.use('/jadwal-kuliah', jadwalKuliahRoute);
router.use('/kehadiran-dosen', kehadiranDosenRoute);
router.use('/nilai-mahasiswa', nilaiMahasiswaRoute);
router.use('/yudisium', yudisiumRoute);
router.use('/laporan/ijazah-transkrip', laporanIjazahRoute);
router.use('/laporan/cetak-realisasi', laporanRealisasiRoute);
router.use('/laporan/cetak-surat', suratKeteranganRoute);
router.use('/laporan/kehadiran-mengajar', laporanKehadiranMengajarRoute);
router.use('/laporan/cetak-mahasiswa-perkelas', laporanMahasiswaPerkelasRoute);
router.use('/laporan/cetak-khs', laporanKhsRoute);
router.use('/tahun-ajaran', tahunAjaranRoute);
router.use('/mata-kuliah', mataKuliahRoute);
router.use('/krs', krsRoute);
router.use('/prodi/lulusan', prodiLulusanRoute);
router.use('/prodi/jadwal-sidang', jadwalSidangRoute);
router.use('/prodi/pendaftar-sidang', pendaftarSidangRoute);
router.use('/prodi/pembimbing-magang', pembimbingMagangRoute);
router.use('/prodi/bimbingan-magang', bimbinganMagangRoute);
router.use('/prodi/pembimbing-ta-skripsi', pembimbingTaSkripsiRoute);
router.use('/prodi/pembimbing-akademik', pembimbingAkademikRoute);
router.use('/prodi/nilai-perkelas', nilaiPerkelasRoute);
router.use('/prodi/voc-dosen-ftid', vocDosenFtidRoute);
router.use('/prodi/voc-ujian-ftid', vocUjianFtidRoute);
router.use('/prodi/kurikulum', kurikulumRoute);
router.use('/prodi/konversi-kurikulum', konversiKurikulumRoute);
router.use('/prodi/biodata-mahasiswa', biodataMahasiswaRoute);
router.use('/sync-finger-a1', createSyncFingerRoute('A1', MENU.SYNC_FINGER_A1_MANAGEMENT));
router.use('/sync-finger-a2', createSyncFingerRoute('A2', MENU.SYNC_FINGER_A2_MANAGEMENT));
router.use('/dinas-cuti-lupa-finger', dinasCutiLupaFingerRoute);
router.use('/report-finger', reportFingerRoute);
router.use('/keuangan/keringanan', keringananRoute);
router.use('/keuangan/tunggakan-mahasiswa', tunggakanMahasiswaRoute);
router.use('/keuangan/tarif-ta-skripsi', tarifTaSkripsiRoute);
router.use('/keuangan/tarif-pembimbing', tarifPembimbingRoute);
router.use('/keuangan/tarif-lain', tarifLainRoute);
router.use('/keuangan/tarif-kuliah', tarifKuliahRoute);
router.use('/keuangan/daftar-potongan', daftarPotonganRoute);
router.use('/keuangan/voc-ujian', vocUjianRoute);
router.use('/keuangan/pembayaran-sertifikasi', pembayaranSertifikasiRoute);
router.use('/keuangan/pembayaran-wisuda', pembayaranWisudaRoute);
router.use('/keuangan/generate-tagihan', tagihanKuliahRoute);
router.use('/keuangan/pembayaran-kuliah', pembayaranKuliahRoute);
router.use('/keuangan/perpanjangan-ta-skripsi', perpanjanganTaSkripsiRoute);
router.use('/keuangan/pembayaran-ta-skripsi', pembayaranTaSkripsiRoute);
router.use('/keuangan/pembayaran-lain', pembayaranLainRoute);
router.use('/keuangan/pembayaran-sp', pembayaranSpRoute);
router.use('/keuangan/laporan', laporanKeuanganRoute);
router.use('/keuangan/akuntansi', akuntansiRoute);
router.use('/keuangan/kasir-dashboard', kasirDashboardRoute);
// Portal self-service Dosen: auth & data terpisah total dari sistem User/Role/Menu/Permission admin.
router.use('/dosen-portal', dosenPortalRoute);
// Portal self-service Mahasiswa: auth & data terpisah total dari sistem User/Role/Menu/Permission admin.
router.use('/mahasiswa-portal', mahasiswaPortalRoute);
router.use('/sim/student-body', simStudentBodyRoute);
router.use('/sim/presentase-kehadiran', simPresentaseKehadiranRoute);
router.use('/sim/kehadiran-kelas', simKehadiranKelasRoute);
router.use('/sim/frs', simFrsRoute);
router.use('/sim/ujian', simLaporanUjianRoute);
router.use('/sim/aktif', laporanAktifRoute);
router.use('/sim/ipk', simIpkRoute);
router.use('/sim/lulusan', simLulusanRoute);
router.use('/sim/nilai-d-e', simNilaiDERoute);
router.use('/sim/kehadiran-mengajar', simKehadiranMengajarRoute);
router.use('/sim/rekapitulasi-pengajaran', simRekapitulasiPengajaranRoute);

module.exports = router;
