const router = require('express').Router();
const authRoute = require('./auth.route');
const userRoute = require('./user.route');
const roleRoute = require('./role.route');
const menuRoute = require('./menu.route');
const golonganKelasRoute = require('./golonganKelas.route');
const jurusanRoute = require('./jurusan.route');
const sumberInformasiRoute = require('./sumberInformasi.route');
const ukuranAlmamaterRoute = require('./ukuranAlmamater.route');
const pembayaranRoute = require('./pembayaran.route');
const dokumenPendaftaranRoute = require('./dokumenPendaftaran.route');
const dokumenKelengkapanRoute = require('./dokumenKelengkapan.route');
const gelombangRoute = require('./gelombang.route');
const pesertaRoute = require('./peserta.route');
const kampusRoute = require('./kampus.route');
const beasiswaRoute = require('./beasiswa.route');
const biayaKuliahRoute = require('./biayaKuliah.route');
const calonMahasiswaRoute = require('./calonMahasiswa.route');
const mahasiswaRoute = require('./mahasiswa.route');
const homeImageRoute = require('./homeImage.route');
const auditLogRoute = require('./auditLog.route');
const karyawanRoute = require('./karyawan.route');
const dosenRoute = require('./dosen.route');
const jadwalKuliahRoute = require('./jadwalKuliah.route');
const kehadiranDosenRoute = require('./kehadiranDosen.route');
const nilaiMahasiswaRoute = require('./nilaiMahasiswa.route');
const yudisiumRoute = require('./yudisium.route');
const laporanIjazahRoute = require('./laporanIjazah.route');
const laporanRealisasiRoute = require('./laporanRealisasi.route');
const suratKeteranganRoute = require('./suratKeterangan.route');
const laporanKehadiranMengajarRoute = require('./laporanKehadiranMengajar.route');
const laporanMahasiswaPerkelasRoute = require('./laporanMahasiswaPerkelas.route');
const laporanKhsRoute = require('./laporanKhs.route');
const tahunAjaranRoute = require('./tahunAjaran.route');
const mataKuliahRoute = require('./mataKuliah.route');
const krsRoute = require('./krs.route');
const prodiLulusanRoute = require('./prodiLulusan.route');
const jadwalSidangRoute = require('./jadwalSidang.route');
const pendaftarSidangRoute = require('./pendaftarSidang.route');
const pembimbingMagangRoute = require('./pembimbingMagang.route');
const pembimbingTaSkripsiRoute = require('./pembimbingTaSkripsi.route');
const pembimbingAkademikRoute = require('./pembimbingAkademik.route');
const nilaiPerkelasRoute = require('./nilaiPerkelas.route');
const bimbinganMagangRoute = require('./bimbinganMagang.route');
const vocDosenFtidRoute = require('./vocDosenFtid.route');
const vocUjianFtidRoute = require('./vocUjianFtid.route');
const kurikulumRoute = require('./kurikulum.route');
const konversiKurikulumRoute = require('./konversiKurikulum.route');
const biodataMahasiswaRoute = require('./biodataMahasiswa.route');
const createSyncFingerRoute = require('./syncFingerLog.route');
const dinasCutiLupaFingerRoute = require('./dinasCutiLupaFinger.route');
const reportFingerRoute = require('./reportFinger.route');
const publicRoute = require('./public.route');
const MENU = require('../constants/menuCodes');

router.use('/public', publicRoute);
router.use('/auth', authRoute);
router.use('/users', userRoute);
router.use('/roles', roleRoute);
router.use('/menus', menuRoute);
router.use('/golongan-kelas', golonganKelasRoute);
router.use('/jurusan', jurusanRoute);
router.use('/sumber-informasi', sumberInformasiRoute);
router.use('/ukuran-almamater', ukuranAlmamaterRoute);
router.use('/pembayaran', pembayaranRoute);
router.use('/dokumen-pendaftaran', dokumenPendaftaranRoute);
router.use('/dokumen-kelengkapan', dokumenKelengkapanRoute);
router.use('/gelombang', gelombangRoute);
router.use('/peserta', pesertaRoute);
router.use('/kampus', kampusRoute);
router.use('/beasiswa', beasiswaRoute);
router.use('/biaya-kuliah', biayaKuliahRoute);
router.use('/calon-mahasiswa', calonMahasiswaRoute);
router.use('/mahasiswa', mahasiswaRoute);
router.use('/home-images', homeImageRoute);
router.use('/audit-logs', auditLogRoute);
router.use('/dosen', dosenRoute);
router.use('/karyawan', karyawanRoute);
router.use('/jadwal-kuliah', jadwalKuliahRoute);
router.use('/kehadiran-dosen', kehadiranDosenRoute);
router.use('/nilai-mahasiswa', nilaiMahasiswaRoute);
router.use('/yudisium', yudisiumRoute);
router.use('/laporan/ijazah-transkrip', laporanIjazahRoute);
router.use('/laporan/cetak-realisasi', laporanRealisasiRoute);
router.use('/laporan/cetak-surat', suratKeteranganRoute);
router.use('/laporan/kehadiran-mengajar', laporanKehadiranMengajarRoute);
router.use('/laporan/cetak-mahasiswa-perkelas', laporanMahasiswaPerkelasRoute);
router.use('/laporan/cetak-khs', laporanKhsRoute);
router.use('/tahun-ajaran', tahunAjaranRoute);
router.use('/mata-kuliah', mataKuliahRoute);
router.use('/krs', krsRoute);
router.use('/prodi/lulusan', prodiLulusanRoute);
router.use('/prodi/jadwal-sidang', jadwalSidangRoute);
router.use('/prodi/pendaftar-sidang', pendaftarSidangRoute);
router.use('/prodi/pembimbing-magang', pembimbingMagangRoute);
router.use('/prodi/bimbingan-magang', bimbinganMagangRoute);
router.use('/prodi/pembimbing-ta-skripsi', pembimbingTaSkripsiRoute);
router.use('/prodi/pembimbing-akademik', pembimbingAkademikRoute);
router.use('/prodi/nilai-perkelas', nilaiPerkelasRoute);
router.use('/prodi/voc-dosen-ftid', vocDosenFtidRoute);
router.use('/prodi/voc-ujian-ftid', vocUjianFtidRoute);
router.use('/prodi/kurikulum', kurikulumRoute);
router.use('/prodi/konversi-kurikulum', konversiKurikulumRoute);
router.use('/prodi/biodata-mahasiswa', biodataMahasiswaRoute);
router.use('/sync-finger-a1', createSyncFingerRoute('A1', MENU.SYNC_FINGER_A1_MANAGEMENT));
router.use('/sync-finger-a2', createSyncFingerRoute('A2', MENU.SYNC_FINGER_A2_MANAGEMENT));
router.use('/dinas-cuti-lupa-finger', dinasCutiLupaFingerRoute);
router.use('/report-finger', reportFingerRoute);

module.exports = router;
