const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'PMB Backend API',
      version: '1.0.0',
      description:
        'REST API for PMB master data: authentication (JWT), user, role, and menu-based RBAC (role akses & menu) management.',
    },
    servers: [
      {
        url: `${process.env.SWAGGER_SERVER_URL || 'http://localhost:3000'}/api`,
        description: 'API base URL',
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
        pesertaBearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'Access token dari POST /peserta/login (berbeda dari token staff/admin)',
        },
        dosenBearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'Access token dari POST /dosen-portal/login (berbeda dari token staff/admin)',
        },
        mahasiswaBearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'Access token dari POST /mahasiswa-portal/login (berbeda dari token staff/admin)',
        },
      },
      parameters: {
        PageParam: {
          name: 'page',
          in: 'query',
          schema: { type: 'integer', default: 1 },
          description: 'Page number',
        },
        LimitParam: {
          name: 'limit',
          in: 'query',
          schema: { type: 'integer', default: 10 },
          description: 'Items per page',
        },
        SearchParam: {
          name: 'search',
          in: 'query',
          schema: { type: 'string' },
          description: 'Search keyword',
        },
        IdParam: {
          name: 'id',
          in: 'path',
          required: true,
          schema: { type: 'integer' },
          description: 'Record ID',
        },
        RoleIdParam: {
          name: 'roleId',
          in: 'path',
          required: true,
          schema: { type: 'integer' },
          description: 'Role ID',
        },
        GolonganKelasIdQueryParam: {
          name: 'golonganKelasId',
          in: 'query',
          schema: { type: 'integer' },
          description: 'Filter jurusan by golongan kelas id',
        },
      },
      schemas: {
        LoginRequest: {
          type: 'object',
          required: ['username', 'password'],
          properties: {
            username: { type: 'string', example: 'superadmin' },
            password: { type: 'string', format: 'password', example: 'Password123!' },
          },
        },
        LoginResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean' },
            message: { type: 'string' },
            data: {
              type: 'object',
              properties: {
                accessToken: { type: 'string' },
                refreshToken: { type: 'string' },
                user: { $ref: '#/components/schemas/User' },
              },
            },
          },
        },
        ForgotPasswordRequest: {
          type: 'object',
          required: ['email'],
          properties: {
            email: { type: 'string', format: 'email' },
          },
        },
        ResetPasswordRequest: {
          type: 'object',
          required: ['token', 'password'],
          properties: {
            token: { type: 'string', description: 'Token mentah dari link di email reset password' },
            password: { type: 'string', format: 'password', minLength: 8 },
          },
        },
        User: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            name: { type: 'string' },
            username: { type: 'string' },
            email: { type: 'string' },
            isActive: { type: 'boolean' },
            roleId: { type: 'integer' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        CreateUserRequest: {
          type: 'object',
          required: ['name', 'username', 'email', 'password', 'roleId'],
          properties: {
            name: { type: 'string' },
            username: { type: 'string' },
            email: { type: 'string' },
            password: { type: 'string' },
            roleId: { type: 'integer' },
            isActive: { type: 'boolean' },
          },
        },
        UpdateUserRequest: {
          type: 'object',
          properties: {
            name: { type: 'string' },
            email: { type: 'string' },
            password: { type: 'string' },
            roleId: { type: 'integer' },
            isActive: { type: 'boolean' },
          },
        },
        Role: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            name: { type: 'string' },
            code: { type: 'string' },
            description: { type: 'string' },
            isActive: { type: 'boolean' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        CreateRoleRequest: {
          type: 'object',
          required: ['name', 'code'],
          properties: {
            name: { type: 'string' },
            code: { type: 'string' },
            description: { type: 'string' },
            isActive: { type: 'boolean' },
          },
        },
        UpdateRoleRequest: {
          type: 'object',
          properties: {
            name: { type: 'string' },
            code: { type: 'string' },
            description: { type: 'string' },
            isActive: { type: 'boolean' },
          },
        },
        Menu: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            parentId: { type: 'integer', nullable: true },
            name: { type: 'string' },
            code: { type: 'string' },
            path: { type: 'string' },
            icon: { type: 'string' },
            orderNumber: { type: 'integer' },
            isActive: { type: 'boolean' },
            isPublic: { type: 'boolean', description: 'true = ditampilkan di navigasi landing page, false = menu admin' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        CreateMenuRequest: {
          type: 'object',
          required: ['name', 'code'],
          properties: {
            parentId: { type: 'integer', nullable: true },
            name: { type: 'string' },
            code: { type: 'string' },
            path: { type: 'string' },
            icon: { type: 'string' },
            orderNumber: { type: 'integer' },
            isActive: { type: 'boolean' },
            isPublic: { type: 'boolean', description: 'true = ditampilkan di navigasi landing page, false = menu admin' },
          },
        },
        UpdateMenuRequest: {
          type: 'object',
          properties: {
            parentId: { type: 'integer', nullable: true },
            name: { type: 'string' },
            code: { type: 'string' },
            path: { type: 'string' },
            icon: { type: 'string' },
            orderNumber: { type: 'integer' },
            isActive: { type: 'boolean' },
            isPublic: { type: 'boolean', description: 'true = ditampilkan di navigasi landing page, false = menu admin' },
          },
        },
        AssignPermissionsRequest: {
          type: 'object',
          required: ['permissions'],
          properties: {
            permissions: {
              type: 'array',
              items: {
                type: 'object',
                required: ['menuId'],
                properties: {
                  menuId: { type: 'integer' },
                  canCreate: { type: 'boolean' },
                  canRead: { type: 'boolean' },
                  canUpdate: { type: 'boolean' },
                  canDelete: { type: 'boolean' },
                },
              },
            },
          },
        },
        GolonganKelas: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            namaKelas: { type: 'string' },
            isDelete: { type: 'boolean' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        CreateGolonganKelasRequest: {
          type: 'object',
          required: ['namaKelas'],
          properties: {
            namaKelas: { type: 'string', example: 'Kelas Reguler' },
          },
        },
        UpdateGolonganKelasRequest: {
          type: 'object',
          properties: {
            namaKelas: { type: 'string' },
          },
        },
        Jurusan: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            golonganKelasId: { type: 'integer' },
            namaJurusan: { type: 'string' },
            foto: { type: 'string', nullable: true, description: 'Base64 data URI foto program studi' },
            prospekKarir: { type: 'string', nullable: true, description: 'Daftar prospek karir, satu item per baris' },
            isDelete: { type: 'boolean' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
            golonganKelas: { $ref: '#/components/schemas/GolonganKelas' },
          },
        },
        CreateJurusanRequest: {
          type: 'object',
          required: ['golonganKelasId', 'namaJurusan'],
          properties: {
            golonganKelasId: { type: 'integer', example: 1 },
            namaJurusan: { type: 'string', example: 'Rekayasa Perangkat Lunak' },
            foto: { type: 'string', description: 'Base64 data URI foto program studi' },
            prospekKarir: { type: 'string', description: 'Daftar prospek karir, satu item per baris' },
          },
        },
        UpdateJurusanRequest: {
          type: 'object',
          properties: {
            golonganKelasId: { type: 'integer' },
            namaJurusan: { type: 'string' },
            foto: { type: 'string' },
            prospekKarir: { type: 'string' },
          },
        },
        SumberInformasi: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            namaInformasi: { type: 'string' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        CreateSumberInformasiRequest: {
          type: 'object',
          required: ['namaInformasi'],
          properties: {
            namaInformasi: { type: 'string', example: 'Media Sosial' },
          },
        },
        UpdateSumberInformasiRequest: {
          type: 'object',
          properties: {
            namaInformasi: { type: 'string' },
          },
        },
        UkuranAlmamater: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            ukuran: { type: 'string' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        CreateUkuranAlmamaterRequest: {
          type: 'object',
          required: ['ukuran'],
          properties: {
            ukuran: { type: 'string', example: 'XL' },
          },
        },
        UpdateUkuranAlmamaterRequest: {
          type: 'object',
          properties: {
            ukuran: { type: 'string' },
          },
        },
        Pembayaran: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            namaPembayaran: { type: 'string' },
            isBeasiswa: { type: 'boolean' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        CreatePembayaranRequest: {
          type: 'object',
          required: ['namaPembayaran'],
          properties: {
            namaPembayaran: { type: 'string', example: 'Biaya Pendaftaran' },
            isBeasiswa: { type: 'boolean', default: false },
          },
        },
        UpdatePembayaranRequest: {
          type: 'object',
          properties: {
            namaPembayaran: { type: 'string' },
            isBeasiswa: { type: 'boolean' },
          },
        },
        DokumenPendaftaran: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            namaPendaftaran: { type: 'string' },
            isWajib: { type: 'boolean' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        CreateDokumenPendaftaranRequest: {
          type: 'object',
          required: ['namaPendaftaran'],
          properties: {
            namaPendaftaran: { type: 'string', example: 'Kartu Keluarga' },
            isWajib: { type: 'boolean', default: false },
          },
        },
        UpdateDokumenPendaftaranRequest: {
          type: 'object',
          properties: {
            namaPendaftaran: { type: 'string' },
            isWajib: { type: 'boolean' },
          },
        },
        DokumenKelengkapan: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            namaKelengkapan: { type: 'string' },
            isWajib: { type: 'boolean' },
            isBeasiswa: { type: 'boolean' },
            file: { type: 'string', format: 'byte', description: 'File dalam bentuk base64 (hanya muncul di detail, tidak di list)' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        CreateDokumenKelengkapanRequest: {
          type: 'object',
          required: ['namaKelengkapan'],
          properties: {
            namaKelengkapan: { type: 'string', example: 'Ijazah Terakhir' },
            isWajib: { type: 'boolean', default: false },
            isBeasiswa: { type: 'boolean', default: false },
            file: { type: 'string', format: 'byte', description: 'Base64 string, boleh dengan prefix data:<mime>;base64,' },
          },
        },
        UpdateDokumenKelengkapanRequest: {
          type: 'object',
          properties: {
            namaKelengkapan: { type: 'string' },
            isWajib: { type: 'boolean' },
            isBeasiswa: { type: 'boolean' },
            file: { type: 'string', format: 'byte' },
          },
        },
        Gelombang: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            namaGelombang: { type: 'string' },
            startDate: { type: 'string', format: 'date' },
            endDate: { type: 'string', format: 'date' },
            deskripsi: { type: 'string', nullable: true },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        CreateGelombangRequest: {
          type: 'object',
          required: ['namaGelombang', 'startDate', 'endDate'],
          properties: {
            namaGelombang: { type: 'string', example: 'Gelombang 1' },
            startDate: { type: 'string', format: 'date', example: '2026-09-01' },
            endDate: { type: 'string', format: 'date', example: '2026-09-30' },
            deskripsi: { type: 'string', nullable: true },
          },
        },
        UpdateGelombangRequest: {
          type: 'object',
          properties: {
            namaGelombang: { type: 'string' },
            startDate: { type: 'string', format: 'date' },
            endDate: { type: 'string', format: 'date' },
            deskripsi: { type: 'string', nullable: true },
          },
        },
        Peserta: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            namaLengkap: { type: 'string' },
            asalSekolah: { type: 'string' },
            golonganKelasId: { type: 'integer' },
            jurusanId: { type: 'integer' },
            noTelepon: { type: 'string' },
            email: { type: 'string' },
            isActive: { type: 'boolean' },
            statusUjian: { type: 'string', enum: ['belum_ujian', 'lulus', 'tidak_lulus'] },
            statusKelulusan: { type: 'string', enum: ['menunggu', 'diterima', 'ditolak'] },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
            golonganKelas: { $ref: '#/components/schemas/GolonganKelas' },
            jurusan: { $ref: '#/components/schemas/Jurusan' },
            biodata: { $ref: '#/components/schemas/PesertaBiodata' },
          },
        },
        PesertaBiodata: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            pesertaId: { type: 'integer' },
            tempatLahir: { type: 'string' },
            tanggalLahir: { type: 'string', format: 'date' },
            jenisKelamin: { type: 'string', enum: ['L', 'P'] },
            agama: { type: 'string' },
            kewarganegaraan: { type: 'string' },
            nik: { type: 'string' },
            namaIbuKandung: { type: 'string' },
            jalan: { type: 'string' },
            rt: { type: 'string' },
            rw: { type: 'string' },
            desaKelurahan: { type: 'string' },
            provinsi: { type: 'string' },
            kabupaten: { type: 'string' },
            kecamatan: { type: 'string' },
            kodePos: { type: 'string' },
            noWhatsapp: { type: 'string' },
            isAgree: { type: 'boolean' },
          },
        },
        LoginPesertaRequest: {
          type: 'object',
          required: ['email', 'password'],
          properties: {
            email: { type: 'string', example: 'budi@example.com' },
            password: { type: 'string', format: 'password' },
          },
        },
        UpdateMyProfileRequest: {
          type: 'object',
          properties: {
            namaLengkap: { type: 'string' },
            asalSekolah: { type: 'string' },
            golonganKelasId: { type: 'integer' },
            jurusanId: { type: 'integer' },
            noTelepon: { type: 'string' },
            email: { type: 'string' },
          },
        },
        SaveBiodataRequest: {
          type: 'object',
          required: [
            'tempatLahir',
            'tanggalLahir',
            'jenisKelamin',
            'agama',
            'kewarganegaraan',
            'nik',
            'namaIbuKandung',
            'jalan',
            'rt',
            'rw',
            'desaKelurahan',
            'provinsi',
            'kabupaten',
            'kecamatan',
            'kodePos',
            'noWhatsapp',
            'isAgree',
          ],
          properties: {
            tempatLahir: { type: 'string', example: 'Jakarta' },
            tanggalLahir: { type: 'string', format: 'date', example: '2005-06-15' },
            jenisKelamin: { type: 'string', enum: ['L', 'P'] },
            agama: { type: 'string', example: 'Islam' },
            kewarganegaraan: { type: 'string', example: 'Indonesia' },
            nik: { type: 'string', example: '3201010000000001' },
            namaIbuKandung: { type: 'string' },
            jalan: { type: 'string' },
            rt: { type: 'string', example: '001' },
            rw: { type: 'string', example: '002' },
            desaKelurahan: { type: 'string' },
            provinsi: { type: 'string' },
            kabupaten: { type: 'string' },
            kecamatan: { type: 'string' },
            kodePos: { type: 'string', example: '12345' },
            noWhatsapp: { type: 'string' },
            isAgree: { type: 'boolean', example: true },
          },
        },
        UploadPesertaDokumenRequest: {
          type: 'object',
          required: ['fileName', 'file'],
          properties: {
            fileName: { type: 'string', example: 'ijazah.pdf' },
            file: {
              type: 'string',
              description: 'Base64 data URI, hanya menerima application/pdf, image/png, atau image/jpeg',
              example: 'data:application/pdf;base64,JVBERi0xLjQK...',
            },
          },
        },
        PesertaDokumenStatus: {
          type: 'object',
          properties: {
            dokumenKelengkapanId: { type: 'integer' },
            namaKelengkapan: { type: 'string' },
            isWajib: { type: 'boolean' },
            isBeasiswa: { type: 'boolean' },
            upload: {
              type: 'object',
              nullable: true,
              properties: {
                id: { type: 'integer' },
                fileName: { type: 'string' },
                file: { type: 'string', description: 'Base64 data URI' },
                updatedAt: { type: 'string', format: 'date-time' },
              },
            },
          },
        },
        RegisterPesertaRequest: {
          type: 'object',
          required: ['namaLengkap', 'asalSekolah', 'golonganKelasId', 'jurusanId', 'noTelepon', 'email'],
          properties: {
            namaLengkap: { type: 'string', example: 'Budi Santoso' },
            asalSekolah: { type: 'string', example: 'SMA Negeri 1 Jakarta' },
            golonganKelasId: { type: 'integer', example: 1 },
            jurusanId: { type: 'integer', example: 1 },
            noTelepon: { type: 'string', example: '081234567890' },
            email: { type: 'string', example: 'budi@example.com' },
          },
        },
        CreatePesertaRequest: {
          type: 'object',
          required: ['namaLengkap', 'asalSekolah', 'golonganKelasId', 'jurusanId', 'noTelepon', 'email'],
          properties: {
            namaLengkap: { type: 'string' },
            asalSekolah: { type: 'string' },
            golonganKelasId: { type: 'integer' },
            jurusanId: { type: 'integer' },
            noTelepon: { type: 'string' },
            email: { type: 'string' },
            isActive: { type: 'boolean' },
          },
        },
        UpdatePesertaRequest: {
          type: 'object',
          properties: {
            namaLengkap: { type: 'string' },
            asalSekolah: { type: 'string' },
            golonganKelasId: { type: 'integer' },
            jurusanId: { type: 'integer' },
            noTelepon: { type: 'string' },
            email: { type: 'string' },
            isActive: { type: 'boolean' },
            statusUjian: { type: 'string', enum: ['belum_ujian', 'lulus', 'tidak_lulus'] },
            statusKelulusan: { type: 'string', enum: ['menunggu', 'diterima', 'ditolak'] },
          },
        },
        Kampus: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            namaKampus: { type: 'string' },
            alamat: { type: 'string', nullable: true },
            telepon: { type: 'string', nullable: true },
            kodePos: { type: 'string', nullable: true },
            email: { type: 'string', nullable: true },
            whatsappNumber: { type: 'string', nullable: true, description: 'Format internasional tanpa +, mis. 6281316455664' },
            facebookUrl: { type: 'string', nullable: true },
            instagramUrl: { type: 'string', nullable: true },
            youtubeUrl: { type: 'string', nullable: true },
            logoUrl: { type: 'string', nullable: true, description: 'Base64 data URI logo website' },
            faviconUrl: { type: 'string', nullable: true, description: 'Base64 data URI favicon website' },
            websiteTitle: { type: 'string', nullable: true, description: 'Judul tab browser (document title) website publik' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        UpdateKampusRequest: {
          type: 'object',
          properties: {
            namaKampus: { type: 'string', example: 'Politeknik Bhakti Kartini' },
            alamat: { type: 'string' },
            telepon: { type: 'string' },
            kodePos: { type: 'string' },
            email: { type: 'string' },
            whatsappNumber: { type: 'string', example: '6281316455664' },
            facebookUrl: { type: 'string' },
            instagramUrl: { type: 'string' },
            youtubeUrl: { type: 'string' },
            logoUrl: { type: 'string', description: 'Base64 data URI logo website' },
            faviconUrl: { type: 'string', description: 'Base64 data URI favicon website' },
            websiteTitle: { type: 'string', example: 'Home - PMB Politeknik Bhakti Kartini' },
          },
        },
        HomeImage: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            heroImage: { type: 'string', nullable: true, description: 'Base64 data URI, gambar hero section' },
            programStudiImage: { type: 'string', nullable: true, description: 'Base64 data URI, gambar section Pilihan Program Studi' },
            kehidupanKampusImage: { type: 'string', nullable: true, description: 'Base64 data URI, gambar kartu "Kehidupan Kampus" pada bento grid' },
            fasilitasLabImage: { type: 'string', nullable: true, description: 'Base64 data URI, foto Lab Pemrograman' },
            fasilitasGedungImage: { type: 'string', nullable: true, description: 'Base64 data URI, foto Gedung Kampus' },
            fasilitasAulaImage: { type: 'string', nullable: true, description: 'Base64 data URI, foto Aula' },
            beasiswaSlide1Image: { type: 'string', nullable: true, description: 'Base64 data URI, slide 1 galeri beasiswa' },
            beasiswaSlide2Image: { type: 'string', nullable: true, description: 'Base64 data URI, slide 2 galeri beasiswa' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        UpdateHomeImagesRequest: {
          type: 'object',
          properties: {
            heroImage: { type: 'string' },
            programStudiImage: { type: 'string' },
            kehidupanKampusImage: { type: 'string' },
            fasilitasLabImage: { type: 'string' },
            fasilitasGedungImage: { type: 'string' },
            fasilitasAulaImage: { type: 'string' },
            beasiswaSlide1Image: { type: 'string' },
            beasiswaSlide2Image: { type: 'string' },
          },
        },
        Beasiswa: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            namaBeasiswa: { type: 'string' },
            slug: { type: 'string' },
            ringkasan: { type: 'string', nullable: true },
            konten: { type: 'string', nullable: true, description: 'HTML konten halaman (h2, p, ol/ul, a didukung)' },
            orderNumber: { type: 'integer' },
            isActive: { type: 'boolean' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        CreateBeasiswaRequest: {
          type: 'object',
          required: ['namaBeasiswa', 'slug'],
          properties: {
            namaBeasiswa: { type: 'string', example: 'Beasiswa Kartu Indonesia Pintar (KIP)' },
            slug: { type: 'string', example: 'kip' },
            ringkasan: { type: 'string' },
            konten: { type: 'string' },
            orderNumber: { type: 'integer' },
            isActive: { type: 'boolean' },
          },
        },
        UpdateBeasiswaRequest: {
          type: 'object',
          properties: {
            namaBeasiswa: { type: 'string' },
            slug: { type: 'string' },
            ringkasan: { type: 'string' },
            konten: { type: 'string' },
            orderNumber: { type: 'integer' },
            isActive: { type: 'boolean' },
          },
        },
        BiayaKuliah: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            judul: { type: 'string' },
            slug: { type: 'string' },
            ringkasan: { type: 'string', nullable: true },
            konten: { type: 'string', nullable: true, description: 'HTML konten halaman, termasuk tabel biaya' },
            orderNumber: { type: 'integer' },
            isActive: { type: 'boolean' },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
          },
        },
        CreateBiayaKuliahRequest: {
          type: 'object',
          required: ['judul', 'slug'],
          properties: {
            judul: { type: 'string', example: 'Biaya Kuliah Mahasiswa Baru 2026/2027' },
            slug: { type: 'string', example: '2026-2027' },
            ringkasan: { type: 'string' },
            konten: { type: 'string' },
            orderNumber: { type: 'integer' },
            isActive: { type: 'boolean' },
          },
        },
        UpdateBiayaKuliahRequest: {
          type: 'object',
          properties: {
            judul: { type: 'string' },
            slug: { type: 'string' },
            ringkasan: { type: 'string' },
            konten: { type: 'string' },
            orderNumber: { type: 'integer' },
            isActive: { type: 'boolean' },
          },
        },
        CalonMahasiswa: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            nama: { type: 'string' },
            asalSekolah: { type: 'string' },
            prodi: { type: 'string' },
            gelombangId: { type: 'integer', nullable: true },
            noTelepon: { type: 'string', nullable: true },
            skemaPembiayaan: { type: 'string', enum: ['beasiswa', 'mandiri'] },
            formulirPendaftaran: { type: 'boolean' },
            lulusTesMasuk: { type: 'boolean' },
            akunBeasiswa: { type: 'boolean', nullable: true, description: 'null = tidak berlaku (N/A)' },
            kelengkapanPersyaratan: { type: 'boolean' },
            statusBeasiswa: { type: 'string', enum: ['diusulkan', 'disetujui', 'ditolak'], nullable: true },
            statusKuliah: { type: 'string', enum: ['menunggu', 'diterima', 'ditolak'] },
            createdBy: { type: 'integer', nullable: true },
            updatedBy: { type: 'integer', nullable: true },
            gelombang: { $ref: '#/components/schemas/Gelombang' },
          },
        },
        CreateCalonMahasiswaRequest: {
          type: 'object',
          required: ['nama', 'asalSekolah', 'prodi'],
          properties: {
            nama: { type: 'string', example: 'Ahmad Fauzi' },
            asalSekolah: { type: 'string', example: 'SMKS YP 17 Cilegon' },
            prodi: { type: 'string', example: 'D4 - Rekayasa Keamanan Siber' },
            gelombangId: { type: 'integer', nullable: true },
            noTelepon: { type: 'string' },
            skemaPembiayaan: { type: 'string', enum: ['beasiswa', 'mandiri'] },
            formulirPendaftaran: { type: 'boolean' },
            lulusTesMasuk: { type: 'boolean' },
            akunBeasiswa: { type: 'boolean', nullable: true },
            kelengkapanPersyaratan: { type: 'boolean' },
            statusBeasiswa: { type: 'string', enum: ['diusulkan', 'disetujui', 'ditolak'], nullable: true },
            statusKuliah: { type: 'string', enum: ['menunggu', 'diterima', 'ditolak'] },
          },
        },
        UpdateCalonMahasiswaRequest: {
          type: 'object',
          properties: {
            nama: { type: 'string' },
            asalSekolah: { type: 'string' },
            prodi: { type: 'string' },
            gelombangId: { type: 'integer', nullable: true },
            noTelepon: { type: 'string' },
            skemaPembiayaan: { type: 'string', enum: ['beasiswa', 'mandiri'] },
            formulirPendaftaran: { type: 'boolean' },
            lulusTesMasuk: { type: 'boolean' },
            akunBeasiswa: { type: 'boolean', nullable: true },
            kelengkapanPersyaratan: { type: 'boolean' },
            statusBeasiswa: { type: 'string', enum: ['diusulkan', 'disetujui', 'ditolak'], nullable: true },
            statusKuliah: { type: 'string', enum: ['menunggu', 'diterima', 'ditolak'] },
          },
        },
        Mahasiswa: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            nim: { type: 'string', example: 'TI20260001' },
            pesertaId: { type: 'integer' },
            namaLengkap: { type: 'string' },
            email: { type: 'string' },
            noTelepon: { type: 'string', nullable: true },
            asalSekolah: { type: 'string', nullable: true },
            golonganKelasId: { type: 'integer' },
            jurusanId: { type: 'integer' },
            tahunMasuk: { type: 'integer' },
            urutan: { type: 'integer' },
            isActive: { type: 'boolean' },
            golonganKelas: { $ref: '#/components/schemas/GolonganKelas' },
            jurusan: { $ref: '#/components/schemas/Jurusan' },
            biodata: { $ref: '#/components/schemas/MahasiswaBiodata' },
          },
        },
        MahasiswaBiodata: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            mahasiswaId: { type: 'integer' },
            tempatLahir: { type: 'string', nullable: true },
            tanggalLahir: { type: 'string', format: 'date', nullable: true },
            agama: { type: 'string', nullable: true },
            kewarganegaraan: { type: 'string', nullable: true },
            noKtp: { type: 'string', nullable: true },
            npwp: { type: 'string', nullable: true },
            jalan: { type: 'string', nullable: true },
            dusun: { type: 'string', nullable: true },
            rt: { type: 'string', nullable: true },
            rw: { type: 'string', nullable: true },
            kelurahan: { type: 'string', nullable: true },
            kodePos: { type: 'string', nullable: true },
            propinsi: { type: 'string', nullable: true },
            jenisTinggal: { type: 'string', nullable: true },
            alatTransportasi: { type: 'string', nullable: true },
            kelas: { type: 'string', nullable: true },
            programStudi: { type: 'string', nullable: true },
            waktuKuliah: { type: 'string', nullable: true },
            statusBelajar: { type: 'string', nullable: true },
            statusKuliah: { type: 'string', nullable: true },
            statusDikti: { type: 'string', nullable: true },
            email: { type: 'string', nullable: true },
            hp: { type: 'string', nullable: true },
            almamater: { type: 'string', nullable: true },
            namaAyah: { type: 'string', nullable: true },
            pekerjaanAyah: { type: 'string', nullable: true },
            namaIbu: { type: 'string', nullable: true },
            pekerjaanIbu: { type: 'string', nullable: true },
          },
        },
        SaveMahasiswaBiodataRequest: {
          type: 'object',
          properties: {
            tempatLahir: { type: 'string' },
            tanggalLahir: { type: 'string', format: 'date', example: '2005-10-31' },
            agama: { type: 'string' },
            kewarganegaraan: { type: 'string', example: 'Indonesia' },
            noKtp: { type: 'string' },
            npwp: { type: 'string' },
            jalan: { type: 'string' },
            dusun: { type: 'string' },
            rt: { type: 'string' },
            rw: { type: 'string' },
            kelurahan: { type: 'string' },
            kodePos: { type: 'string' },
            propinsi: { type: 'string' },
            jenisTinggal: { type: 'string', example: 'Orang Tua' },
            alatTransportasi: { type: 'string', example: 'Kendaraan Pribadi' },
            kelas: { type: 'string', example: 'B' },
            programStudi: { type: 'string' },
            waktuKuliah: { type: 'string', example: 'Pagi' },
            statusBelajar: { type: 'string', example: 'Non Shift' },
            statusKuliah: { type: 'string', example: 'Baru' },
            statusDikti: { type: 'string', example: 'Mahasiswa Reguler' },
            email: { type: 'string' },
            hp: { type: 'string' },
            almamater: { type: 'string' },
            namaAyah: { type: 'string' },
            pekerjaanAyah: { type: 'string' },
            namaIbu: { type: 'string' },
            pekerjaanIbu: { type: 'string' },
          },
        },
        UpdateMahasiswaRequest: {
          type: 'object',
          properties: {
            nim: { type: 'string' },
            namaLengkap: { type: 'string' },
            email: { type: 'string' },
            noTelepon: { type: 'string', nullable: true },
            asalSekolah: { type: 'string', nullable: true },
            golonganKelasId: { type: 'integer' },
            jurusanId: { type: 'integer' },
            tahunMasuk: { type: 'integer' },
            isActive: { type: 'boolean' },
          },
        },
        GenerateMahasiswaRequest: {
          type: 'object',
          required: ['tahunMasuk', 'jurusanPrefixes'],
          properties: {
            tahunMasuk: { type: 'integer', example: 2026 },
            jurusanPrefixes: {
              type: 'object',
              description: 'Map jurusanId (string) -> prefix NIM khusus jurusan tersebut',
              additionalProperties: { type: 'string' },
              example: { '1': 'TI', '2': 'SI' },
            },
            pesertaIds: {
              type: 'array',
              items: { type: 'integer' },
              description: 'Opsional. Jika diisi, hanya peserta ini yang digenerate; jika kosong, seluruh peserta yang lulus & diterima dan belum memiliki NIM akan digenerate.',
            },
          },
        },
        AuditLog: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            actorType: { type: 'string', enum: ['staff', 'peserta', 'public'] },
            actorId: { type: 'integer', nullable: true },
            actorName: { type: 'string', nullable: true },
            actorEmail: { type: 'string', nullable: true },
            method: { type: 'string', example: 'POST' },
            module: { type: 'string', example: 'Jurusan' },
            action: { type: 'string', example: 'create' },
            path: { type: 'string', example: '/api/jurusan' },
            description: { type: 'string', example: 'Admin PMB membuat data baru pada Jurusan' },
            statusCode: { type: 'integer', example: 201 },
            ipAddress: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
          },
        },
      },
    },
    security: [{ bearerAuth: [] }],
  },
  apis: ['./src/routes/*.js'],
};

module.exports = swaggerJsdoc(options);
